#!/bin/bash

export PGHOST=${POSTGRES_HOST}
export PGPORT=${POSTGRES_PORT}
export PGUSER=${POSTGRES_PORTAL_USER}
export PGPASSWORD=${POSTGRES_PORTAL_PASS:-"$POSTGRES_PORTAL_USER"}
export PGDATABASE=${POSTGRES_PORTAL_DB:-"$POSTGRES_PORTAL_USER"}

check_postgresql_isready() {
  until pg_isready -q -d $PGDATABASE; do
    sleep 2
  done
}

check_postgresql() {
  check_postgresql_isready

  echo "Waiting PostgreSQL ready..."
  until su - postgres -lc 'psql -t -A -c \\du' | grep -q "${POSTGRES_PORTAL_USER}"; do
    sleep 2
  done
  echo "PostgreSQL is ready."
}

check_minio() {
  echo "Waiting MinIO ready..."
  until /usr/bin/curl -s http://${CSGHUB_PORTAL_S3_ENDPOINT}/minio/health/live; do
    sleep 2
  done
  echo "MinIO is ready."
}

#wait_for_jobs() {
#  echo "Waiting init jobs done..."
#  until [ "$(supervisorctl status | grep init-job | grep -v mirror | grep -c RUNNING)" -eq 0 ]; do
#    echo "Waiting for init jobs to finish..."
#    sleep 2
#  done
#  echo "All init jobs completed."
#}

check_postgresql

if [ "$MINIO_ROOT_USER" == "minio" ]; then
  check_minio
fi

#wait_for_jobs

echo "Initializing database migrations..."
/usr/bin/csghub-portal migration init

echo "Running database migrations..."
/usr/bin/csghub-portal migration migrate

echo "Starting portal..."
cd /var/log/csghub-portal && exec /usr/bin/csghub-portal start server