#!/bin/bash

set -e

check_server() {
  echo "Waiting CSGHub-Server ready..."
  until /usr/bin/curl -s -o /dev/null http://127.0.0.1:8080/api/v1/tags; do
    sleep 2
  done
  echo "CSGHub-Server is ready."
}

check_server

echo "Starting rproxy..."
exec /usr/bin/csghub-server start rproxy