#!/bin/bash

set -e

if [ -f "/etc/resolv.conf" ]; then
  if ! grep -q '127.0.0.1' /etc/resolv.conf; then
    cp -f /etc/resolv.conf /tmp/resolv.conf.bak
    sed '0,/nameserver/s//nameserver 127.0.0.1\n&/' /tmp/resolv.conf.bak > /etc/resolv.conf
  fi
fi

if [ "$(pgrep -l -c -x dnsmasq)" -eq 1 ]; then
    pkill dnsmasq
fi

echo "Starting dnsmasq..."
exec /usr/sbin/dnsmasq --conf-dir=/etc/dnsmasq.d --no-daemon