#!/bin/bash

set -e

export MINIO_ROOT_USER=${S3_ACCESS_KEY:-"$MINIO_ROOT_USER"}
export MINIO_ROOT_PASSWORD=${S3_ACCESS_SECRET:-"$MINIO_ROOT_PASSWORD"}
export MINIO_REGION_NAME=${S3_REGION:-"$MINIO_REGION_NAME"}
export MINIO_DATA="/var/opt/minio/data"

if [ ! -d "$MINIO_DATA" ]; then
  mkdir -p $MINIO_DATA 2>/dev/null
fi

if [ -z "$MINIO_ROOT_USER" ] || [ -z "$MINIO_ROOT_PASSWORD" ]; then
  echo "environment MINIO_ROOT_USER and MINIO_ROOT_PASSWORD must be provided."
fi

if [[ "$(pgrep -l -c -x minio)" -eq 1 ]]; then
  echo "minio is already running."
else
  echo "start minio..."
  exec /usr/bin/minio server --address :9000 --console-address :9001 $MINIO_DATA
fi