#!/bin/bash

set -e

check_server() {
  echo "Waiting CSGHub-Server ready..."
  until /usr/bin/curl -s -o /dev/null http://127.0.0.1:8080/api/v1/tags; do
    sleep 2
  done
  echo "CSGHub-Server is ready."
}

check_portal() {
  echo "Waiting CSGHub-Portal ready..."
  until /usr/bin/curl -s http://127.0.0.1:8090; do
    sleep 2
  done
  echo "CSGHub-Portal is ready."
}

check_server
check_portal

if [ -f "/etc/nginx/nginx.conf.sample" ]; then
  envsubst < /etc/nginx/nginx.conf.sample > /etc/nginx/nginx.conf
fi

if [ -f "/etc/nginx/nginx.conf" ]; then
  echo "Starting nginx..."
  exec /usr/sbin/nginx -c /etc/nginx/nginx.conf
fi