#!/bin/bash

PGDATA="/var/opt/postgresql/data"
UNIX_SOCK="/var/run/postgresql"

# Remove Extra Config Directories
if [ -d "/etc/postgresql" ]; then
  rm -rf /etc/postgresql
fi

# Initialized Directories
if [ ! -d "$PGDATA" ]; then
  mkdir -p $PGDATA 2>/dev/null
fi

# Initialized Database
if [ -f "$PGDATA/PG_VERSION" ]; then
  echo "postgresql database is already initialized."
else
  echo "postgresql database is not initialized."
  echo "Start initialization..."
  mkdir -p $PGDATA
  initdb --auth=trust --encoding=UTF8 -D $PGDATA
fi

postgres_running() {
  if [ -f "$PGDATA/postmaster.pid" ]; then
    POSTGRES_PID=$(head -1 "$PGDATA/postmaster.pid" | tr -d '[:space:]')
    if [ -n "$POSTGRES_PID" ]; then
      PROGRESS_EXISTS=$(ps -ef | awk '$1 == '"$POSTGRES_PID"' {print $NF}')
      if [ -n "$PROGRESS_EXISTS" ]; then
        kill -9 "$POSTGRES_PID"
        return 0
      else
        return 1
      fi
    else
      return 1
    fi
  else
    return 1
  fi
}

if postgres_running; then
  rm -rf $UNIX_SOCK/.s.PGSQL.5432 $PGDATA/postmaster.pid 2>/dev/null
fi

echo "Starting PostgreSQL database..."
exec /usr/bin/postgres -D "$PGDATA" -k "$UNIX_SOCK"
