#!/bin/bash

set -e

REDIS_DATA="/var/opt/redis"

if [ -f "$UNIX_SOCK/redis.sock" ]; then
  echo "redis is already running."
else
  echo "start redis..."
  exec /usr/bin/redis-server /etc/redis/redis.conf --daemonize no --logfile "" --appendonly yes --appendfilename "redis.aof" --dir $REDIS_DATA
fi