#!/bin/bash

set -e

echo "Create htpasswd file."
htpasswd -Bb -c /etc/registry/.htpasswd $REGISTRY_USERNAME $REGISTRY_PASSWORD

if [ -f "/etc/registry/config.yml.sample" ]; then
  envsubst < /etc/registry/config.yml.sample > /etc/registry/config.yml
fi

if [[ "$(pgrep -l -c -x registry)" -eq 1 ]]; then
  echo "distribution registry is already running."
else
  if [ -f "/etc/registry/.htpasswd" ]; then
    echo "start distribution registry..."
    exec /usr/bin/registry serve /etc/registry/config.yml
  else
    echo "htpasswd auth file cannot be found."
  fi
fi