{{- if .Values.tcp -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.controller.tcp.annotations }}
  annotations: {{ toYaml .Values.controller.tcp.annotations | nindent 4 }}
{{- end }}
  name: {{ include "ingress-nginx.fullname" . }}-tcp
  namespace: {{ include "ingress-nginx.namespace" . }}
data:
  {{- if .Values.global.gitaly.enabled }}
  22: {{ printf "%s/%s:22" .Release.Namespace (include "gitlab-shell.internal.domain" .) }}
  {{- else }}
  22: {{ printf "%s/%s:22" .Release.Namespace (include "gitea.internal.domain" .) }}
  {{- end }}
{{- end }}